// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGcT5mMolr_ZiJSy2ju4mEyCMQhcCbBUY',
    appId: '1:1094202630315:web:695573a30292886cff57ee',
    messagingSenderId: '1094202630315',
    projectId: 'madexam-2aca3',
    authDomain: 'madexam-2aca3.firebaseapp.com',
    storageBucket: 'madexam-2aca3.firebasestorage.app',
    measurementId: 'G-148ELG43C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZsIXfqNzlBBJBylVzGygOMlqBaCnOAx8',
    appId: '1:1094202630315:android:5a87d6e1198b43a3ff57ee',
    messagingSenderId: '1094202630315',
    projectId: 'madexam-2aca3',
    storageBucket: 'madexam-2aca3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBfy1k-Zuxp-CYP1dVHJB9kD6ef8KI0DQ',
    appId: '1:1094202630315:ios:a5ef35c45ba387afff57ee',
    messagingSenderId: '1094202630315',
    projectId: 'madexam-2aca3',
    storageBucket: 'madexam-2aca3.firebasestorage.app',
    iosBundleId: 'com.example.madexam30',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBfy1k-Zuxp-CYP1dVHJB9kD6ef8KI0DQ',
    appId: '1:1094202630315:ios:a5ef35c45ba387afff57ee',
    messagingSenderId: '1094202630315',
    projectId: 'madexam-2aca3',
    storageBucket: 'madexam-2aca3.firebasestorage.app',
    iosBundleId: 'com.example.madexam30',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGcT5mMolr_ZiJSy2ju4mEyCMQhcCbBUY',
    appId: '1:1094202630315:web:0c54f5d230f79e30ff57ee',
    messagingSenderId: '1094202630315',
    projectId: 'madexam-2aca3',
    authDomain: 'madexam-2aca3.firebaseapp.com',
    storageBucket: 'madexam-2aca3.firebasestorage.app',
    measurementId: 'G-101W0HDXG4',
  );
}
